/* ── Mock Data for Trend Flow Dashboard ── */

export const SEASONS = ["24SS", "24FW", "25SS", "25FW", "26SS", "26FW"];
export const ZONINGS = ["전체", "럭셔리", "스포츠/아웃도어", "캐주얼/스트리트", "SPA/매스"];
export const CATEGORIES = ["전체", "컬러", "소재", "실루엣", "아이템", "스타일"];
export const CATEGORY_MAP = {
  "전체": "all",
  "컬러": "color",
  "소재": "material",
  "실루엣": "silhouette",
  "아이템": "item",
  "스타일": "style",
};

export const ORIGIN_LABELS = {
  runway_led: "Runway-led",
  capital_driven: "Capital",
  viral_meme: "Viral",
  market_organic: "Organic",
  unknown: "—",
};

export const ORIGIN_COLORS = {
  runway_led: "#3266ad",
  capital_driven: "#8B5CF6",
  viral_meme: "#D97706",
  market_organic: "#059669",
  unknown: "#999",
};

export const SIGNAL_LABELS = [
  { key: "expert", label: "전문가" },
  { key: "runway", label: "런웨이" },
  { key: "celeb", label: "셀럽" },
  { key: "search", label: "검색" },
  { key: "market", label: "마켓" },
];

export const MOCK_KEYWORDS = [
  {
    id: 1,
    keyword: "burgundy",
    confidence: 85,
    category: "color",
    origin: "runway_led",
    pool: "A",
    zoning: ["럭셔리", "SPA/매스"],
    signals: { expert: 0.8, runway: 0.9, celeb: 0.45, search: 0.65, market: 0.55 },
    signalDetails: {
      expert: "WGSN + Pantone",
      runway: "12 디자이너",
      celeb: "스파이크 2건",
      search: "+45% vs 전기",
      market: "47개 상품",
    },
    timeline: [
      { season: "24FW", strength: 20, label: "런웨이 5" },
      { season: "25SS", strength: 40, label: "런웨이 8 · WGSN" },
      { season: "25FW", strength: 70, label: "+셀럽 · 마켓 23개" },
      { season: "26SS", strength: 90, label: "마켓 47개 · 검색 +45%" },
    ],
    brands: [
      { brand: "Nike", count: 12 },
      { brand: "Descente", count: 8 },
      { brand: "Youth", count: 7 },
      { brand: "Lemaire", count: 5 },
    ],
  },
  {
    id: 2,
    keyword: "oversized tailoring",
    confidence: 78,
    category: "silhouette",
    origin: "runway_led",
    pool: "A",
    zoning: ["럭셔리", "캐주얼/스트리트"],
    signals: { expert: 0.7, runway: 0.85, celeb: 0.5, search: 0.55, market: 0.4 },
    signalDetails: {
      expert: "WGSN",
      runway: "9 디자이너",
      celeb: "착용 4건",
      search: "+32% vs 전기",
      market: "28개 상품",
    },
    timeline: [
      { season: "25SS", strength: 35, label: "런웨이 9" },
      { season: "25FW", strength: 55, label: "+WGSN · 셀럽 2" },
      { season: "26SS", strength: 78, label: "마켓 28개 · 검색 +32%" },
    ],
    brands: [
      { brand: "Lemaire", count: 6 },
      { brand: "Marithe", count: 5 },
      { brand: "Coor", count: 4 },
    ],
  },
  {
    id: 3,
    keyword: "quiet luxury",
    confidence: 74,
    category: "style",
    origin: "runway_led",
    pool: "A",
    zoning: ["럭셔리"],
    signals: { expert: 0.75, runway: 0.65, celeb: 0.6, search: 0.6, market: 0.5 },
    signalDetails: {
      expert: "BoF + Vogue",
      runway: "6 디자이너",
      celeb: "착용 5건",
      search: "+28% vs 전기",
      market: "31개 상품",
    },
    timeline: [
      { season: "24FW", strength: 30, label: "런웨이 4 · BoF" },
      { season: "25SS", strength: 50, label: "+셀럽 3" },
      { season: "25FW", strength: 65, label: "마켓 18개" },
      { season: "26SS", strength: 74, label: "마켓 31개 · 검색 +28%" },
    ],
    brands: [
      { brand: "Lemaire", count: 9 },
      { brand: "Coor", count: 3 },
    ],
  },
  {
    id: 4,
    keyword: "wide leg",
    confidence: 72,
    category: "silhouette",
    origin: "market_organic",
    pool: "A",
    zoning: ["캐주얼/스트리트", "SPA/매스"],
    signals: { expert: 0.5, runway: 0.6, celeb: 0.4, search: 0.7, market: 0.8 },
    signalDetails: {
      expert: "Tagwalk",
      runway: "7 디자이너",
      celeb: "착용 3건",
      search: "+55% vs 전기",
      market: "62개 상품",
    },
    timeline: [
      { season: "24SS", strength: 40, label: "마켓 15개" },
      { season: "24FW", strength: 55, label: "마켓 28개 · 검색 +20%" },
      { season: "25SS", strength: 65, label: "마켓 45개 · 런웨이 5" },
      { season: "25FW", strength: 72, label: "마켓 62개 · 검색 +55%" },
    ],
    brands: [
      { brand: "Youth", count: 14 },
      { brand: "MLB", count: 11 },
      { brand: "Marithe", count: 8 },
      { brand: "Blankroom", count: 6 },
    ],
  },
  {
    id: 5,
    keyword: "leather",
    confidence: 68,
    category: "material",
    origin: "runway_led",
    pool: "A",
    zoning: ["럭셔리", "캐주얼/스트리트"],
    signals: { expert: 0.65, runway: 0.7, celeb: 0.55, search: 0.5, market: 0.45 },
    signalDetails: {
      expert: "WGSN",
      runway: "8 디자이너",
      celeb: "착용 4건",
      search: "+22% vs 전기",
      market: "35개 상품",
    },
    timeline: [
      { season: "25SS", strength: 30, label: "런웨이 8" },
      { season: "25FW", strength: 50, label: "+WGSN · 셀럽 2" },
      { season: "26SS", strength: 68, label: "마켓 35개" },
    ],
    brands: [
      { brand: "Lemaire", count: 7 },
      { brand: "Descente", count: 5 },
      { brand: "Nike", count: 4 },
    ],
  },
  {
    id: 6,
    keyword: "sheer",
    confidence: 62,
    category: "material",
    origin: "runway_led",
    pool: "A",
    zoning: ["럭셔리"],
    signals: { expert: 0.6, runway: 0.75, celeb: 0.3, search: 0.4, market: 0.25 },
    signalDetails: {
      expert: "WGSN",
      runway: "10 디자이너",
      celeb: "착용 1건",
      search: "+15% vs 전기",
      market: "12개 상품",
    },
    timeline: [
      { season: "25SS", strength: 40, label: "런웨이 10 · WGSN" },
      { season: "25FW", strength: 55, label: "+셀럽 1" },
      { season: "26SS", strength: 62, label: "마켓 12개 · 검색 +15%" },
    ],
    brands: [
      { brand: "Lemaire", count: 3 },
    ],
  },
  {
    id: 7,
    keyword: "maxi skirt",
    confidence: 58,
    category: "item",
    origin: "runway_led",
    pool: "A",
    zoning: ["럭셔리", "SPA/매스"],
    signals: { expert: 0.5, runway: 0.65, celeb: 0.35, search: 0.45, market: 0.4 },
    signalDetails: {
      expert: "Tagwalk",
      runway: "6 디자이너",
      celeb: "착용 2건",
      search: "+18% vs 전기",
      market: "22개 상품",
    },
    timeline: [
      { season: "25FW", strength: 35, label: "런웨이 6" },
      { season: "26SS", strength: 58, label: "+Tagwalk · 마켓 22개" },
    ],
    brands: [
      { brand: "Marithe", count: 5 },
      { brand: "Coor", count: 4 },
      { brand: "Youth", count: 3 },
    ],
  },
  {
    id: 8,
    keyword: "gorpcore",
    confidence: 55,
    category: "style",
    origin: "viral_meme",
    pool: "B",
    zoning: ["스포츠/아웃도어", "캐주얼/스트리트"],
    signals: { expert: 0.2, runway: 0.1, celeb: 0.6, search: 0.7, market: 0.65 },
    signalDetails: {
      expert: "—",
      runway: "2 디자이너",
      celeb: "착용 6건",
      search: "+80% vs 전기",
      market: "45개 상품",
    },
    timeline: [
      { season: "24FW", strength: 25, label: "소셜 밈" },
      { season: "25SS", strength: 45, label: "셀럽 4 · 검색 +50%" },
      { season: "25FW", strength: 55, label: "마켓 45개 · 검색 +80%" },
    ],
    brands: [
      { brand: "NorthFace", count: 15 },
      { brand: "Descente", count: 10 },
      { brand: "Nike", count: 8 },
      { brand: "Kolon Sport", count: 6 },
    ],
  },
  {
    id: 9,
    keyword: "ballet flats",
    confidence: 51,
    category: "item",
    origin: "capital_driven",
    pool: "A",
    zoning: ["럭셔리", "SPA/매스"],
    signals: { expert: 0.4, runway: 0.3, celeb: 0.7, search: 0.5, market: 0.35 },
    signalDetails: {
      expert: "Vogue",
      runway: "3 디자이너",
      celeb: "캠페인 3건",
      search: "+35% vs 전기",
      market: "18개 상품",
    },
    timeline: [
      { season: "25SS", strength: 30, label: "캠페인 런칭" },
      { season: "25FW", strength: 45, label: "셀럽 착용 · 검색 +35%" },
      { season: "26SS", strength: 51, label: "마켓 18개" },
    ],
    brands: [
      { brand: "Lemaire", count: 4 },
      { brand: "Coor", count: 3 },
    ],
  },
  {
    id: 10,
    keyword: "blouson jacket",
    confidence: 48,
    category: "item",
    origin: "market_organic",
    pool: "B",
    zoning: ["캐주얼/스트리트", "스포츠/아웃도어"],
    signals: { expert: 0.25, runway: 0.2, celeb: 0.3, search: 0.5, market: 0.65 },
    signalDetails: {
      expert: "—",
      runway: "2 디자이너",
      celeb: "착용 2건",
      search: "+25% vs 전기",
      market: "38개 상품",
    },
    timeline: [
      { season: "24FW", strength: 20, label: "마켓 10개" },
      { season: "25SS", strength: 35, label: "마켓 22개 · 검색 +12%" },
      { season: "25FW", strength: 48, label: "마켓 38개 · 검색 +25%" },
    ],
    brands: [
      { brand: "Descente", count: 8 },
      { brand: "Nike", count: 6 },
      { brand: "NorthFace", count: 5 },
    ],
  },
  {
    id: 11,
    keyword: "mesh",
    confidence: 45,
    category: "material",
    origin: "viral_meme",
    pool: "B",
    zoning: ["캐주얼/스트리트"],
    signals: { expert: 0.2, runway: 0.3, celeb: 0.5, search: 0.55, market: 0.3 },
    signalDetails: {
      expert: "—",
      runway: "3 디자이너",
      celeb: "착용 3건",
      search: "+40% vs 전기",
      market: "15개 상품",
    },
    timeline: [
      { season: "25SS", strength: 25, label: "틱톡 확산" },
      { season: "25FW", strength: 40, label: "셀럽 3 · 검색 +40%" },
      { season: "26SS", strength: 45, label: "마켓 15개" },
    ],
    brands: [
      { brand: "Nike", count: 5 },
      { brand: "Youth", count: 4 },
    ],
  },
  {
    id: 12,
    keyword: "cherry red",
    confidence: 42,
    category: "color",
    origin: "capital_driven",
    pool: "B",
    zoning: ["캐주얼/스트리트", "SPA/매스"],
    signals: { expert: 0.3, runway: 0.25, celeb: 0.6, search: 0.4, market: 0.25 },
    signalDetails: {
      expert: "—",
      runway: "3 디자이너",
      celeb: "캠페인 2건",
      search: "+20% vs 전기",
      market: "14개 상품",
    },
    timeline: [
      { season: "25FW", strength: 25, label: "캠페인 런칭" },
      { season: "26SS", strength: 42, label: "셀럽 착용 · 마켓 14개" },
    ],
    brands: [
      { brand: "MLB", count: 4 },
      { brand: "Marithe", count: 3 },
    ],
  },
  {
    id: 13,
    keyword: "cobalt blue",
    confidence: 28,
    category: "color",
    origin: "unknown",
    pool: "B",
    zoning: [],
    signals: { expert: 0.15, runway: 0.3, celeb: 0.1, search: 0.15, market: 0.1 },
    signalDetails: {
      expert: "—",
      runway: "3 디자이너",
      celeb: "—",
      search: "+5% vs 전기",
      market: "4개 상품",
    },
    timeline: [
      { season: "25FW", strength: 15, label: "런웨이 3" },
      { season: "26SS", strength: 28, label: "마켓 4개" },
    ],
    brands: [
      { brand: "Nike", count: 2 },
      { brand: "Descente", count: 2 },
    ],
  },
];
