/**
 * WGSN 26SS Expert Keywords — Seed Data
 * Source: WGSN 77 reports (NotebookLM analysis)
 * Generated from: WGSN_26SS_KEYWORD_MASTER.md
 */

export const EXPERT_KEYWORDS_26SS = [
  // ─── Color: Tier 1 (10+ sources) ───
  { keyword: "blue_aura", keyword_kr: "블루 오라", category: "color", season: "26SS", source_count: 13, tier: 1, pool: "A", source: "wgsn", themes: ["Gelato Pastels"], description: "파스텔 포인트 컬러. 은은한 블루 톤으로 Gelato Pastels 테마의 핵심.", runway_keyword: "blue", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "celestial_yellow", keyword_kr: "셀레스티얼 옐로우", category: "color", season: "26SS", source_count: 12, tier: 1, pool: "A", source: "wgsn", themes: ["Joyous Brights"], description: "밝은 옐로우. Joyous Brights 팔레트의 핵심 컬러로 에너지와 낙관을 표현.", runway_keyword: "yellow", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "dusted_grape", keyword_kr: "더스티드 그레이프", category: "color", season: "26SS", source_count: 12, tier: 1, pool: "A", source: "wgsn", themes: ["Berry Tones"], description: "보라/포도 톤. Berry Tones 팔레트에서 성숙하고 깊이 있는 컬러로 주목.", runway_keyword: "purple", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "optic_white", keyword_kr: "옵틱 화이트", category: "color", season: "26SS", source_count: 10, tier: 1, pool: "A", source: "wgsn", themes: ["Minimalist Base"], description: "깨끗한 화이트 베이스. 미니멀리즘의 기본 컬러로 시즌 전반에 걸쳐 활용.", runway_keyword: "white", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "classic_navy", keyword_kr: "클래식 네이비", category: "color", season: "26SS", source_count: 10, tier: 1, pool: "A", source: "wgsn", themes: ["Nautical", "Base"], description: "기본 네이비. Nautical 테마와 베이스 컬러로서 시즌 내내 안정적 수요.", runway_keyword: "navy", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "black", keyword_kr: "블랙", category: "color", season: "26SS", source_count: 10, tier: 1, pool: null, source: "wgsn", themes: ["Base"], description: "기본 블랙. 시즌 불문 베이스 컬러.", runway_keyword: "black", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "transformative_teal", keyword_kr: "트랜스포머티브 틸", category: "color", season: "26SS", source_count: 10, tier: 1, pool: "B", source: "wgsn", themes: ["2026 COTY"], description: "2026 올해의 컬러(COTY). WGSN+Coloro 선정 — 자연과 기술의 균형을 상징하는 블루그린.", runway_keyword: "teal", f_and_f_relevance: "medium", review_status: null, review_comment: null, reviewer: null },

  // ─── Color: Tier 2 (8~9 sources) ───
  { keyword: "pink_frost", keyword_kr: "핑크 프로스트", category: "color", season: "26SS", source_count: 9, tier: 2, pool: "A", source: "wgsn", themes: ["Pretty Feminine"], description: "페미닌 파스텔 핑크. Pretty Feminine 테마의 핵심 컬러.", runway_keyword: "pink", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "amber_haze", keyword_kr: "앰버 헤이즈", category: "color", season: "26SS", source_count: 9, tier: 2, pool: null, source: "wgsn", themes: ["Warm Neutrals"], description: "따뜻한 앰버 톤. 뉴트럴 팔레트에서 따뜻함을 더하는 포인트.", runway_keyword: "amber", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "sage_green", keyword_kr: "세이지 그린", category: "color", season: "26SS", source_count: 9, tier: 2, pool: "A", source: "wgsn", themes: ["Nature", "Outdoor"], description: "자연 그린. 아웃도어/자연 테마와 연결되는 안정감 있는 그린.", runway_keyword: "sage", f_and_f_relevance: "medium", review_status: null, review_comment: null, reviewer: null },
  { keyword: "chalk", keyword_kr: "초크", category: "color", season: "26SS", source_count: 9, tier: 2, pool: null, source: "wgsn", themes: ["Neutral Base"], description: "뉴트럴 오프화이트. 화이트보다 따뜻하고 부드러운 톤.", runway_keyword: "ivory", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "cherry_lacquer", keyword_kr: "체리 라커", category: "color", season: "26SS", source_count: 8, tier: 2, pool: "A", source: "wgsn", themes: ["Statement Reds"], description: "레드 포인트. 광택감 있는 체리 레드로 Statement Reds 팔레트의 핵심.", runway_keyword: "red", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "peach_jelly", keyword_kr: "피치 젤리", category: "color", season: "26SS", source_count: 8, tier: 2, pool: "A", source: "wgsn", themes: ["Gelato Pastels"], description: "파스텔 피치. Gelato Pastels 팔레트의 따뜻한 파스텔 톤.", runway_keyword: "peach", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "jelly_mint", keyword_kr: "젤리 민트", category: "color", season: "26SS", source_count: 8, tier: 2, pool: "A", source: "wgsn", themes: ["Gelato Pastels"], description: "파스텔 민트. Gelato Pastels 팔레트의 시원한 파스텔 톤.", runway_keyword: "mint", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "midnight_blue", keyword_kr: "미드나잇 블루", category: "color", season: "26SS", source_count: 8, tier: 2, pool: null, source: "wgsn", themes: ["Dark Tones"], description: "다크 블루. 네이비보다 깊은 톤으로 다크 팔레트의 핵심.", runway_keyword: "navy", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "lava_red", keyword_kr: "라바 레드", category: "color", season: "26SS", source_count: 8, tier: 2, pool: "A", source: "wgsn", themes: ["Statement Reds"], description: "레드 포인트. 용암처럼 강렬한 레드.", runway_keyword: "red", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "chocolate_sauce", keyword_kr: "초콜릿 소스", category: "color", season: "26SS", source_count: 8, tier: 2, pool: null, source: "wgsn", themes: ["Dark Browns"], description: "블랙 대체 브라운. 블랙 대신 깊은 초콜릿 브라운으로 세련된 무드 연출.", runway_keyword: "brown", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "vivid_yellow", keyword_kr: "비비드 옐로우", category: "color", season: "26SS", source_count: 8, tier: 2, pool: "A", source: "wgsn", themes: ["Joyous Brights"], description: "밝은 옐로우. Celestial Yellow보다 채도가 높은 선명한 옐로우.", runway_keyword: "yellow", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "robust_red", keyword_kr: "로버스트 레드", category: "color", season: "26SS", source_count: 8, tier: 2, pool: "A", source: "wgsn", themes: ["Statement Reds"], description: "레드 포인트. 강인하고 묵직한 느낌의 레드.", runway_keyword: "red", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "future_grey", keyword_kr: "퓨처 그레이", category: "color", season: "26SS", source_count: 8, tier: 2, pool: null, source: "wgsn", themes: ["Neutral Base"], description: "뉴트럴 그레이. 미래적이고 세련된 톤의 그레이.", runway_keyword: "gray", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "crimson", keyword_kr: "크림슨", category: "color", season: "26SS", source_count: 8, tier: 2, pool: "A", source: "wgsn", themes: ["Statement Reds"], description: "레드 포인트. 깊고 진한 크림슨 레드.", runway_keyword: "red", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "classic_beige", keyword_kr: "클래식 베이지", category: "color", season: "26SS", source_count: 8, tier: 2, pool: null, source: "wgsn", themes: ["Neutral Base"], description: "뉴트럴 베이지. 시즌 불문 기본 베이스 컬러.", runway_keyword: "beige", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },

  // ─── Color: Tier 3 (6~7 sources) ───
  { keyword: "electric_fuchsia", keyword_kr: "일렉트릭 퓨샤", category: "color", season: "26SS", source_count: 7, tier: 3, pool: "A", source: "wgsn", themes: ["Joyous Brights"], description: "밝은 퓨샤 핑크. Joyous Brights의 에너지 넘치는 핫 핑크.", runway_keyword: "pink", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "thrift_pink", keyword_kr: "스리프트 핑크", category: "color", season: "26SS", source_count: 7, tier: 3, pool: null, source: "wgsn", themes: ["Pretty Feminine"], description: "빈티지 느낌의 핑크. Pretty Feminine 테마의 레트로 핑크.", runway_keyword: "pink", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "sea_kelp", keyword_kr: "씨 켈프", category: "color", season: "26SS", source_count: 7, tier: 3, pool: null, source: "wgsn", themes: ["Nature Tones"], description: "해초 그린. 자연에서 영감받은 깊은 올리브/그린 톤.", runway_keyword: "olive", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "circular_grey", keyword_kr: "서큘러 그레이", category: "color", season: "26SS", source_count: 7, tier: 3, pool: null, source: "wgsn", themes: ["Neutral"], description: "순환/지속 가능성을 상징하는 뉴트럴 그레이 톤.", runway_keyword: "gray", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "blue_gleam", keyword_kr: "블루 글림", category: "color", season: "26SS", source_count: 7, tier: 3, pool: "A", source: "wgsn", themes: ["Gelato Pastels"], description: "밝은 파스텔 블루. Gelato Pastels의 반짝이는 블루.", runway_keyword: "blue", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "retro_green", keyword_kr: "레트로 그린", category: "color", season: "26SS", source_count: 7, tier: 3, pool: null, source: "wgsn", themes: ["Retro", "80s"], description: "80년대 영감의 레트로 그린 톤.", runway_keyword: "green", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },

  // ─── Material: Tier 1 (7+ sources) ───
  { keyword: "sheer", keyword_kr: "시어/투명", category: "material", season: "26SS", source_count: 11, tier: 1, pool: "A", source: "wgsn", themes: ["Pretty Feminine", "City To Beach"], description: "시폰, 오간자 — 레이어링, Day-to-Night 핵심 소재. 이번 시즌 가장 지배적인 패브릭.", runway_keyword: "sheer", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "lace", keyword_kr: "레이스", category: "material", season: "26SS", source_count: 11, tier: 1, pool: "A", source: "wgsn", themes: ["Pretty Feminine", "Dark Romance"], description: "Pretty Feminine과 Dark Romance 양쪽에서 핵심 소재. 관능미와 여성성.", runway_keyword: "lace", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "knit_jersey", keyword_kr: "니트/저지", category: "material", season: "26SS", source_count: 10, tier: 1, pool: "A", source: "wgsn", themes: ["Comfort", "Cut & Sew"], description: "라운지웨어, Cut & Sew 기본. 편안함과 실용성의 기본 소재.", runway_keyword: "knit", f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },
  { keyword: "cotton", keyword_kr: "코튼", category: "material", season: "26SS", source_count: 7, tier: 1, pool: null, source: "wgsn", themes: ["Sustainability"], description: "친환경 인증(BCI, GOTS), 장수명 소재. 지속 가능성 키워드와 직결.", runway_keyword: "cotton", f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },
  { keyword: "leather", keyword_kr: "레더", category: "material", season: "26SS", source_count: 7, tier: 1, pool: "A", source: "wgsn", themes: ["Statement", "Low Key Luxury"], description: "광택/질감 — 아우터, 하의에 활용. 럭셔리 시그널.", runway_keyword: "leather", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },

  // ─── Material: Tier 2 (4~6 sources) ───
  { keyword: "denim", keyword_kr: "데님", category: "material", season: "26SS", source_count: 6, tier: 2, pool: "A", source: "wgsn", themes: ["Y2K", "Officewear"], description: "Y2K, 오피스코어, 리워크드 데님. 다양한 테마에서 재해석.", runway_keyword: "denim", f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },
  { keyword: "linen", keyword_kr: "리넨", category: "material", season: "26SS", source_count: 5, tier: 2, pool: null, source: "wgsn", themes: ["Resort", "Summer Tailoring"], description: "리조트, 여름 테일러링. 시원한 천연소재의 대표.", runway_keyword: "linen", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "hemp", keyword_kr: "헴프", category: "material", season: "26SS", source_count: 5, tier: 2, pool: "B", source: "wgsn", themes: ["Sustainability"], description: "친환경 혼방, 내구성. 지속 가능성 포캐스트의 핵심 소재.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "jacquard", keyword_kr: "자카드", category: "material", season: "26SS", source_count: 5, tier: 2, pool: null, source: "wgsn", themes: ["Texture", "Low Key Luxury"], description: "톤온톤, 은은한 장식. 3D 텍스처 트렌드의 핵심 기법.", runway_keyword: "jacquard", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "twill", keyword_kr: "트윌", category: "material", season: "26SS", source_count: 5, tier: 2, pool: null, source: "wgsn", themes: ["Workwear", "Officewear"], description: "워크웨어, 오피스웨어 기본 원단. 내구성과 격식의 조화.", runway_keyword: null, f_and_f_relevance: "medium", review_status: null, review_comment: null, reviewer: null },
  { keyword: "satin", keyword_kr: "새틴", category: "material", season: "26SS", source_count: 4, tier: 2, pool: null, source: "wgsn", themes: ["Low Key Luxury"], description: "무광/은은한 광택, Low Key Luxury. 절제된 럭셔리 표현.", runway_keyword: "satin", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "lyocell_tencel", keyword_kr: "텐셀/리오셀", category: "material", season: "26SS", source_count: 4, tier: 2, pool: "B", source: "wgsn", themes: ["Sustainability"], description: "친환경, 드레이프. 지속 가능성 포캐스트 소재.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "crochet", keyword_kr: "크로셰", category: "material", season: "26SS", source_count: 4, tier: 2, pool: "A", source: "wgsn", themes: ["Boho", "Beach"], description: "보헤미안, 비치 커버업. 수공예적 텍스처.", runway_keyword: "crochet", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },

  // ─── Material: Tier 3 (2~3 sources) ───
  { keyword: "poplin", keyword_kr: "포플린", category: "material", season: "26SS", source_count: 3, tier: 3, pool: null, source: "wgsn", themes: ["Classic Shirt"], description: "클래식 셔츠 원단. 깔끔한 표면감.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "suede", keyword_kr: "스웨이드", category: "material", season: "26SS", source_count: 3, tier: 3, pool: null, source: "wgsn", themes: ["Low Key Luxury"], description: "Low Key Luxury. 부드러운 질감의 럭셔리 소재.", runway_keyword: "suede", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "viscose", keyword_kr: "비스코스", category: "material", season: "26SS", source_count: 3, tier: 3, pool: null, source: "wgsn", themes: ["Sustainability"], description: "FSC 인증 권장. 드레이프성 좋은 재생 소재.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "merino_wool", keyword_kr: "메리노 울", category: "material", season: "26SS", source_count: 3, tier: 3, pool: null, source: "wgsn", themes: ["Performance", "Sporty"], description: "사계절, 스포티. 기능성과 럭셔리의 교차점.", runway_keyword: "wool", f_and_f_relevance: "medium", review_status: null, review_comment: null, reviewer: null },
  { keyword: "silk", keyword_kr: "실크", category: "material", season: "26SS", source_count: 2, tier: 3, pool: null, source: "wgsn", themes: ["Luxury Texture"], description: "두피온, 질감 강조. 럭셔리 텍스처 소재.", runway_keyword: "silk", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "ripstop", keyword_kr: "립스톱", category: "material", season: "26SS", source_count: 2, tier: 3, pool: null, source: "wgsn", themes: ["Functional", "Workwear"], description: "기능성, 워크웨어. 내구성 중심의 기술 소재.", runway_keyword: null, f_and_f_relevance: "medium", review_status: null, review_comment: null, reviewer: null },
  { keyword: "canvas", keyword_kr: "캔버스", category: "material", season: "26SS", source_count: 2, tier: 3, pool: null, source: "wgsn", themes: ["Workwear"], description: "작업복 테마. 견고한 면직물.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },

  // ─── Silhouette: Tier 1 (15+ sources) ───
  { keyword: "oversized", keyword_kr: "오버사이즈/릴랙스드", category: "silhouette", season: "26SS", source_count: 30, tier: 1, pool: "A", source: "wgsn", themes: ["Mega Trend"], description: "가장 지배적인 실루엣. 전 복종에 걸쳐 릴랙스드 핏이 기본.", runway_keyword: "oversized", f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },
  { keyword: "wide_leg", keyword_kr: "와이드 레그", category: "silhouette", season: "26SS", source_count: 22, tier: 1, pool: "A", source: "wgsn", themes: ["Mega Trend"], description: "하의 1순위 실루엣. 와이드 팬츠/트라우저가 기본 핏으로 정착.", runway_keyword: "wide", f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },
  { keyword: "straight_leg", keyword_kr: "스트레이트 레그", category: "silhouette", season: "26SS", source_count: 20, tier: 1, pool: "A", source: "wgsn", themes: ["Mega Trend"], description: "와이드 대안, 가장 빠른 성장세. 깔끔한 직선 실루엣.", runway_keyword: "straight", f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },

  // ─── Silhouette: Tier 2 (10~15 sources) ───
  { keyword: "cropped", keyword_kr: "크롭", category: "silhouette", season: "26SS", source_count: 15, tier: 2, pool: "A", source: "wgsn", themes: ["Youth", "Layering"], description: "상의/아우터 기장. 크롭 길이로 레이어링과 비율 조정.", runway_keyword: "crop", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "sculpted_shoulder", keyword_kr: "파워 숄더/스컬프티드", category: "silhouette", season: "26SS", source_count: 14, tier: 2, pool: "A", source: "wgsn", themes: ["80s Glamour"], description: "80년대 핵심 — 아우터/상의. 구조적인 어깨 라인으로 파워풀한 실루엣. +225% YoY 급상승.", runway_keyword: "structured", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "barrel_leg", keyword_kr: "배럴/벌룬 레그", category: "silhouette", season: "26SS", source_count: 12, tier: 2, pool: "A", source: "wgsn", themes: ["New Volume"], description: "신규 부상 — 곡선 하의. 와이드를 넘어 둥글게 부풀린 곡선형 레그.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "skinny_slim", keyword_kr: "스키니/슬림", category: "silhouette", season: "26SS", source_count: 11, tier: 2, pool: "A", source: "wgsn", themes: ["2010 Revival"], description: "2010 Revival — 재테스트 중. 스키니핏의 복귀 시그널.", runway_keyword: "slim", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },

  // ─── Silhouette: Tier 3 (6~9 sources) ───
  { keyword: "high_rise", keyword_kr: "하이 라이즈/하이 웨이스트", category: "silhouette", season: "26SS", source_count: 8, tier: 3, pool: null, source: "wgsn", themes: ["Waist Focus"], description: "하의 웨이스트 라인. 허리 강조 트렌드와 연결.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "slouchy", keyword_kr: "슬라우치", category: "silhouette", season: "26SS", source_count: 8, tier: 3, pool: null, source: "wgsn", themes: ["Pyjama Dressing"], description: "파자마 드레싱 연관. 나른하게 흘러내리는 실루엣.", runway_keyword: "relaxed", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "short_short", keyword_kr: "숏 숏/미니", category: "silhouette", season: "26SS", source_count: 7, tier: 3, pool: null, source: "wgsn", themes: ["Sporty", "Festival"], description: "스포티/페스티벌. 짧은 기장의 쇼츠.", runway_keyword: "mini", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "boxy", keyword_kr: "박시", category: "silhouette", season: "26SS", source_count: 7, tier: 3, pool: null, source: "wgsn", themes: ["Relaxed"], description: "재킷, 티셔츠. 각진 박스형 실루엣.", runway_keyword: "boxy", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "waist_focus", keyword_kr: "허리 강조", category: "silhouette", season: "26SS", source_count: 7, tier: 3, pool: "A", source: "wgsn", themes: ["80s Glamour", "Tailoring"], description: "80년대 + 테일러링. 벨트, 코르셋, 핀턱 등으로 허리 라인 부각.", runway_keyword: "fitted", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "a_line", keyword_kr: "A라인", category: "silhouette", season: "26SS", source_count: 7, tier: 3, pool: null, source: "wgsn", themes: ["Classic"], description: "스커트, 반바지. A자로 벌어지는 클래식 실루엣.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "capri", keyword_kr: "카프리/7부", category: "silhouette", season: "26SS", source_count: 6, tier: 3, pool: "A", source: "wgsn", themes: ["2010 Revival"], description: "2010 Revival. 7부 기장 팬츠의 재부상.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "low_rise", keyword_kr: "로우 라이즈", category: "silhouette", season: "26SS", source_count: 6, tier: 3, pool: "A", source: "wgsn", themes: ["2010 Revival"], description: "2010 Revival. 로우라이즈 웨이스트 라인의 복귀.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },

  // ─── Silhouette: Tier 4 (3~5 sources) ───
  { keyword: "drop_shoulder", keyword_kr: "드롭 숄더", category: "silhouette", season: "26SS", source_count: 5, tier: 4, pool: null, source: "wgsn", themes: ["Relaxed"], description: "릴랙스 상의. 어깨 라인이 아래로 떨어지는 편안한 핏.", runway_keyword: "relaxed", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "column_pencil", keyword_kr: "컬럼/펜슬", category: "silhouette", season: "26SS", source_count: 4, tier: 4, pool: null, source: "wgsn", themes: ["Tailoring"], description: "스커트 핏. 몸에 밀착되는 직선형 스커트.", runway_keyword: "fitted", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "flared_bootcut", keyword_kr: "플레어/부트컷", category: "silhouette", season: "26SS", source_count: 3, tier: 4, pool: null, source: "wgsn", themes: ["Retro"], description: "레트로 하의. 무릎 아래로 벌어지는 실루엣.", runway_keyword: "flared", f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },

  // ─── Item: Tier 1 (8+ sources) ───
  { keyword: "tank_top_vest", keyword_kr: "탱크탑/니트 조끼", category: "item", season: "26SS", source_count: 11, tier: 1, pool: "A", source: "wgsn", themes: ["90s Minimal", "Layering"], description: "90년대 미니멀, 레이어링 핵심 아이템. 단독 또는 레이어링 베이스.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "polo_shirt", keyword_kr: "폴로 셔츠", category: "item", season: "26SS", source_count: 9, tier: 1, pool: "A", source: "wgsn", themes: ["Clubhouse", "New Prep"], description: "Clubhouse, New Prep 테마 핵심. 컨트리클럽 스포티 미학.", runway_keyword: null, f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },
  { keyword: "trench_coat", keyword_kr: "트렌치코트", category: "item", season: "26SS", source_count: 8, tier: 1, pool: "A", source: "wgsn", themes: ["Reworked Classics", "80s"], description: "Reworked Classics, 80년대 재해석. 장수명 + 현대적 업그레이드 아우터.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "blazer", keyword_kr: "블레이저", category: "item", season: "26SS", source_count: 8, tier: 1, pool: "A", source: "wgsn", themes: ["Nu-niforms", "Smarten Up"], description: "Nu-niforms, Smarten Up — 새 출근복의 핵심 아우터. 릴랙스 테일러링.", runway_keyword: null, f_and_f_relevance: "medium", review_status: null, review_comment: null, reviewer: null },
  { keyword: "tshirt_graphic_tee", keyword_kr: "티셔츠/그래픽 티", category: "item", season: "26SS", source_count: 8, tier: 1, pool: "A", source: "wgsn", themes: ["Breton Stripe", "Graphic"], description: "브르통 스트라이프, 그래픽 프린트. 일상 기본 아이템의 재해석.", runway_keyword: null, f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },

  // ─── Item: Tier 2 (5~7 sources) ───
  { keyword: "cargo_pants", keyword_kr: "카고 팬츠", category: "item", season: "26SS", source_count: 7, tier: 2, pool: "A", source: "wgsn", themes: ["Utility", "Great Outdoors"], description: "Utility, Great Outdoors. 유틸리티 포켓이 특징인 기능성 팬츠.", runway_keyword: null, f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },
  { keyword: "tracksuit", keyword_kr: "트랙수트/트랙팬츠", category: "item", season: "26SS", source_count: 6, tier: 2, pool: "A", source: "wgsn", themes: ["Retro Replay", "Sporticism"], description: "Retro Replay, 스포티즘. 레트로 트랙수트의 현대적 재해석.", runway_keyword: null, f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },
  { keyword: "field_jacket", keyword_kr: "필드 재킷", category: "item", season: "26SS", source_count: 6, tier: 2, pool: "A", source: "wgsn", themes: ["Future Commuter", "Workwear"], description: "Future Commuter, 워크웨어. 유틸리티 아우터의 대표.", runway_keyword: null, f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },
  { keyword: "capri_trousers", keyword_kr: "카프리 트라우저", category: "item", season: "26SS", source_count: 5, tier: 2, pool: "A", source: "wgsn", themes: ["2010 Revival"], description: "2010 Revival. 7부 기장의 복귀.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "hoodie", keyword_kr: "후디", category: "item", season: "26SS", source_count: 5, tier: 2, pool: null, source: "wgsn", themes: ["Comfort", "Preppy Crop"], description: "Comfort, 프레피 크롭. 편안함과 스포티 감성의 기본 아이템.", runway_keyword: null, f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },

  // ─── Item: Tier 3 (2~4 sources) ───
  { keyword: "cardigan", keyword_kr: "가디건", category: "item", season: "26SS", source_count: 4, tier: 3, pool: null, source: "wgsn", themes: ["Layering", "Preppy"], description: "레이어링, 프레피. 계절 간 전환 핵심 아이템.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "resort_shirt", keyword_kr: "리조트 셔츠/캠프 셔츠", category: "item", season: "26SS", source_count: 4, tier: 3, pool: null, source: "wgsn", themes: ["Refined Resort"], description: "Refined Resort. 오픈 카라, 릴랙스 핏의 리조트 셔츠.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "trucker_jacket", keyword_kr: "트러커/데님 재킷", category: "item", season: "26SS", source_count: 4, tier: 3, pool: "A", source: "wgsn", themes: ["Reworked Classics"], description: "Reworked Classics. 클래식 데님 재킷의 현대적 재해석.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "short_shorts", keyword_kr: "숏 쇼츠", category: "item", season: "26SS", source_count: 4, tier: 3, pool: null, source: "wgsn", themes: ["Sporty", "Festival"], description: "스포티, 페스티벌. 짧은 기장의 액티브 쇼츠.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "bomber_jacket", keyword_kr: "봄버 재킷", category: "item", season: "26SS", source_count: 4, tier: 3, pool: null, source: "wgsn", themes: ["Classic Outerwear"], description: "클래식 아우터. 리버시블/소재 변형으로 재등장.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "camisole_bralette", keyword_kr: "캐미솔/브라렛", category: "item", season: "26SS", source_count: 4, tier: 3, pool: null, source: "wgsn", themes: ["Pretty Feminine"], description: "Pretty Feminine. 여성성 강조 이너웨어 아우터화.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "anorak", keyword_kr: "아노락", category: "item", season: "26SS", source_count: 3, tier: 3, pool: null, source: "wgsn", themes: ["Functional Layering"], description: "기능성 레이어링. 풀오버 형태의 기능성 아우터.", runway_keyword: null, f_and_f_relevance: "medium", review_status: null, review_comment: null, reviewer: null },
  { keyword: "football_jersey", keyword_kr: "풋볼 저지", category: "item", season: "26SS", source_count: 3, tier: 3, pool: "B", source: "wgsn", themes: ["Sportscore", "FIFA 2026"], description: "2026 월드컵 연계, 스포츠코어. 이벤트 드리븐 아이템.", runway_keyword: null, f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },
  { keyword: "statement_mule", keyword_kr: "스테이트먼트 뮬", category: "item", season: "26SS", source_count: 3, tier: 3, pool: null, source: "wgsn", themes: ["Office", "Going Out"], description: "오피스, 외출용. 포인트 슈즈.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "loafer", keyword_kr: "로퍼", category: "item", season: "26SS", source_count: 2, tier: 3, pool: null, source: "wgsn", themes: ["Nu-niforms"], description: "Nu-niforms. 새 출근복과 매칭되는 클래식 슈즈.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "belt_bag", keyword_kr: "벨트백", category: "item", season: "26SS", source_count: 2, tier: 3, pool: "B", source: "wgsn", themes: ["Utility"], description: "유틸리티 액세서리. 핸즈프리 실용 가방.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },

  // ─── Style / Macro Theme ───
  { keyword: "city_to_beach", keyword_kr: "시티 투 비치/리파인드 리조트", category: "style", season: "26SS", source_count: 19, tier: 1, pool: "A", source: "wgsn", themes: ["City To Beach", "Refined Resort"], description: "리조트↔도심 다목적, Modern Mariner. 11+8개 소스 통합. +33% YoY.", runway_keyword: null, f_and_f_relevance: "medium", review_status: null, review_comment: null, reviewer: null },
  { keyword: "pretty_feminine", keyword_kr: "프리티 페미닌/뉴 로맨틱", category: "style", season: "26SS", source_count: 11, tier: 1, pool: "A", source: "wgsn", themes: ["Pretty Feminine", "Nu Romantic"], description: "레이스, 러플, 리본, 플로럴. 여성성과 로맨티시즘. +0.8 ppt 점유율 증가.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "clubhouse_new_prep", keyword_kr: "클럽하우스/뉴 프레피", category: "style", season: "26SS", source_count: 13, tier: 1, pool: "A", source: "wgsn", themes: ["Clubhouse", "New Prep"], description: "프레피, 컨트리클럽, 스포티. +148% Preppy Stripes YoY.", runway_keyword: null, f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },
  { keyword: "nu_niforms", keyword_kr: "뉴니폼/워크 익스피리언스", category: "style", season: "26SS", source_count: 6, tier: 2, pool: "A", source: "wgsn", themes: ["Nu-niforms", "Work Experience"], description: "릴랙스 테일러링, 새 출근복. +0.5 ppt 오피스웨어 점유율 증가.", runway_keyword: null, f_and_f_relevance: "medium", review_status: null, review_comment: null, reviewer: null },
  { keyword: "reworked_classics", keyword_kr: "리워크드 클래식", category: "style", season: "26SS", source_count: 5, tier: 2, pool: "A", source: "wgsn", themes: ["Reworked Classics"], description: "클래식 장수명, 현대적 업그레이드. +56~87% YoY.", runway_keyword: null, f_and_f_relevance: "high", review_status: null, review_comment: null, reviewer: null },
  { keyword: "80s_glamour", keyword_kr: "80년대 글래머", category: "style", season: "26SS", source_count: 6, tier: 2, pool: "A", source: "wgsn", themes: ["80s Glamour"], description: "파워 숄더, 허리 강조, 글래머. +1.4 ppt 점유율 증가. +225% Sculpted Shoulder YoY.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "2010_revival", keyword_kr: "2010 리바이벌/인디 슬리즈", category: "style", season: "26SS", source_count: 5, tier: 2, pool: "A", source: "wgsn", themes: ["2010 Revival", "Indie Sleaze"], description: "스키니, 브릿팝, Messy Girl. 런웨이에서 확인된 부상 테마.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "fandom_foodies", keyword_kr: "팬덤 푸디/키치 그래픽", category: "style", season: "26SS", source_count: 3, tier: 3, pool: "B", source: "wgsn", themes: ["Fandom Foodies"], description: "그래픽/F&B 모티프. MLB, Youth 그래픽 참고.", runway_keyword: null, f_and_f_relevance: "medium", review_status: null, review_comment: null, reviewer: null },
  { keyword: "offline_dating", keyword_kr: "오프라인 데이팅/아날로그 향수", category: "style", season: "26SS", source_count: 3, tier: 3, pool: "B", source: "wgsn", themes: ["Offline Dating"], description: "라이프스타일/아날로그 향수. 그래픽 모티프 참고.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "haunted_cabaret", keyword_kr: "헌티드 카바레/다크 로맨스", category: "style", season: "26SS", source_count: 3, tier: 3, pool: "B", source: "wgsn", themes: ["Haunted Cabaret", "Dark Romance"], description: "APAC 여성복 니치. 캐주얼/스트리트 일부 적용 가능.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "messy_girl", keyword_kr: "메시 걸", category: "style", season: "26SS", source_count: 2, tier: 3, pool: "B", source: "wgsn", themes: ["Messy Girl"], description: "소셜/Youth 기반. 반항적 스타일링, 2010 Revival과 연결.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "scarf_modular", keyword_kr: "스카프 모듈러 스타일링", category: "style", season: "26SS", source_count: 2, tier: 3, pool: "B", source: "wgsn", themes: ["Scarf Modular"], description: "스윔/리조트 액세서리. 스카프를 다양한 방식으로 활용하는 스타일링.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },

  // ─── Social/Data-driven signals ───
  { keyword: "boho_chic", keyword_kr: "보호 시크 스타일", category: "style", season: "26SS", source_count: 1, tier: 3, pool: "B", source: "wgsn", themes: ["Social Buzz"], description: "RedNote 3.29억 뷰. 소셜 미디어 데이터 기반 버즈 키워드.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
  { keyword: "nautical_style", keyword_kr: "노티컬 스타일", category: "style", season: "26SS", source_count: 1, tier: 3, pool: "B", source: "wgsn", themes: ["Social Buzz", "Nautical"], description: "RedNote 1.68억 뷰. City To Beach 테마와 연결되는 소셜 버즈.", runway_keyword: null, f_and_f_relevance: null, review_status: null, review_comment: null, reviewer: null },
];
